'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Carrera
    Public Property CarreraId As System.Guid
    Public Property FacultadId As System.Guid
    Public Property Carrera1 As String

    Public Overridable Property Facultad As Facultad
    Public Overridable Property Clases As ICollection(Of Clases) = New HashSet(Of Clases)
    Public Overridable Property Estudiantes As ICollection(Of Estudiantes) = New HashSet(Of Estudiantes)

End Class
