'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Clases
    Public Property ClaseId As System.Guid
    Public Property Clase As String
    Public Property CarreraId As System.Guid

    Public Overridable Property Carrera As Carrera
    Public Overridable Property ClasesEstudiante As ICollection(Of ClasesEstudiante) = New HashSet(Of ClasesEstudiante)

End Class
