'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ClasesEstudiante
    Public Property Id As System.Guid
    Public Property ClaseId As System.Guid
    Public Property EstudianteId As System.Guid
    Public Property CreadoPorUsuarioId As System.Guid
    Public Property ModificadoPorUsuarioId As System.Guid
    Public Property FechaDeCreacion As Date
    Public Property FechaDeModificacion As Date

    Public Overridable Property Clases As Clases
    Public Overridable Property Estudiantes As Estudiantes

End Class
