'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class ProyectoEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=ProyectoEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Carrera() As DbSet(Of Carrera)
    Public Overridable Property Clases() As DbSet(Of Clases)
    Public Overridable Property ClasesEstudiante() As DbSet(Of ClasesEstudiante)
    Public Overridable Property Departamento() As DbSet(Of Departamento)
    Public Overridable Property Estudiantes() As DbSet(Of Estudiantes)
    Public Overridable Property Facultad() As DbSet(Of Facultad)
    Public Overridable Property Municipio() As DbSet(Of Municipio)
    Public Overridable Property Rol() As DbSet(Of Rol)
    Public Overridable Property usuarios() As DbSet(Of usuarios)

End Class
