'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Estudiantes
    Public Property EstudiantesId As System.Guid
    Public Property Nombre As String
    Public Property Apellido As String
    Public Property CiudadId As System.Guid
    Public Property MunicipioId As System.Guid
    Public Property CarreraId As System.Guid
    Public Property CreadoPorUsuarioId As System.Guid
    Public Property ModificadoPorUsuarioId As System.Guid
    Public Property FechadeCreacion As Date
    Public Property FechadeModificacion As Date
    Public Property Correo As String
    Public Property Telefono As String
    Public Property EstadoId As Byte
    Public Property UsuarioId As System.Guid

    Public Overridable Property Carrera As Carrera
    Public Overridable Property ClasesEstudiante As ICollection(Of ClasesEstudiante) = New HashSet(Of ClasesEstudiante)
    Public Overridable Property Departamento As Departamento
    Public Overridable Property Municipio As Municipio
    Public Overridable Property usuarios As usuarios

End Class
