'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Facultad
    Public Property FacultadId As System.Guid
    Public Property Facultad1 As String

    Public Overridable Property Carrera As ICollection(Of Carrera) = New HashSet(Of Carrera)

End Class
