'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Municipio
    Public Property MunicipioId As System.Guid
    Public Property DepartamentoId As System.Guid
    Public Property Municipio1 As String

    Public Overridable Property Departamento As Departamento
    Public Overridable Property Estudiantes As ICollection(Of Estudiantes) = New HashSet(Of Estudiantes)

End Class
