'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Rol
    Public Property RolId As System.Guid
    Public Property Rol1 As String

    Public Overridable Property usuarios As ICollection(Of usuarios) = New HashSet(Of usuarios)

End Class
