'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class usuarios
    Public Property UsuarioId As System.Guid
    Public Property NombreUsuario As String
    Public Property Contrasena As Byte()
    Public Property RolId As System.Guid

    Public Overridable Property Estudiantes As ICollection(Of Estudiantes) = New HashSet(Of Estudiantes)
    Public Overridable Property Rol As Rol

End Class
